/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BLL.GestionMatricula;
import javax.swing.JOptionPane;

/**
 *
 * @author labctr
 */
public class frmRegistroCalificaciones extends javax.swing.JInternalFrame {

    private final String titulo = "Registro de Calificaciones";
    private GestionMatricula matriculaBll = new GestionMatricula();

    private boolean Validar() {
        float nota = (float) this.snnValor.getValue();
        if (nota == 0.f) {
            vtnPrincipal.verMensaje("Calificacion no válida", titulo, JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    private void consultarMatricula() {
        String numero = this.txtNumeroMatricula.getText();
        matriculaBll.consultar(numero);
        this.txtDatosMatricula.setText(matriculaBll.imprimir());

    }

    private String Calificar() throws Exception {

        float nota = (float) this.snnValor.getValue();
        String mensaje = matriculaBll.calificar(nota);
        matriculaBll.archivar();
        return mensaje;
    }

    public frmRegistroCalificaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistroCalificaciones = new javax.swing.JPanel();
        lblNumeroMatricula = new javax.swing.JLabel();
        txtNumeroMatricula = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDatosMatricula = new javax.swing.JTextArea();
        pnlCalificacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        snnValor = new javax.swing.JSpinner();
        btnGuardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        pnlRegistroCalificaciones.setBackground(new java.awt.Color(255, 204, 204));
        pnlRegistroCalificaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Calificaciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Century Schoolbook L", 1, 24))); // NOI18N

        lblNumeroMatricula.setFont(new java.awt.Font("Century Schoolbook L", 0, 18)); // NOI18N
        lblNumeroMatricula.setText("N° Matrícula:");
        lblNumeroMatricula.setToolTipText("");

        txtNumeroMatricula.setFont(new java.awt.Font("Century Schoolbook L", 0, 14)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Century Schoolbook L", 0, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon("/home/labctr/NetBeansProjects/Ejercicio3U3/iconos/iconfinder_system-search_118797.png")); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtDatosMatricula.setEditable(false);
        txtDatosMatricula.setColumns(20);
        txtDatosMatricula.setFont(new java.awt.Font("Century Schoolbook L", 0, 14)); // NOI18N
        txtDatosMatricula.setRows(5);
        jScrollPane2.setViewportView(txtDatosMatricula);

        pnlCalificacion.setBackground(new java.awt.Color(255, 153, 153));
        pnlCalificacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calificación: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook L", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 0, 14)); // NOI18N
        jLabel1.setText("Valor:");

        snnValor.setFont(new java.awt.Font("Century Schoolbook L", 0, 14)); // NOI18N
        snnValor.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(20.0f), Float.valueOf(0.1f)));

        btnGuardar.setFont(new java.awt.Font("Century Schoolbook L", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon("/home/labctr/NetBeansProjects/Ejercicio3U3/iconos/savetheapplication_guardar_2958.png")); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCalificacionLayout = new javax.swing.GroupLayout(pnlCalificacion);
        pnlCalificacion.setLayout(pnlCalificacionLayout);
        pnlCalificacionLayout.setHorizontalGroup(
            pnlCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCalificacionLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(snnValor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(29, 29, 29))
        );
        pnlCalificacionLayout.setVerticalGroup(
            pnlCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCalificacionLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(snnValor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRegistroCalificacionesLayout = new javax.swing.GroupLayout(pnlRegistroCalificaciones);
        pnlRegistroCalificaciones.setLayout(pnlRegistroCalificacionesLayout);
        pnlRegistroCalificacionesLayout.setHorizontalGroup(
            pnlRegistroCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroCalificacionesLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblNumeroMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroCalificacionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlRegistroCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );
        pnlRegistroCalificacionesLayout.setVerticalGroup(
            pnlRegistroCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroCalificacionesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlRegistroCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroMatricula)
                    .addComponent(txtNumeroMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pnlRegistroCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pnlRegistroCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            consultarMatricula();
        } catch (Exception e) {
            vtnPrincipal.verMensaje("Error al buscar la Matrícula" + e.toString(), titulo, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (Validar()) {
                String mensaje = this.Calificar();
                vtnPrincipal.verMensaje(mensaje, titulo, JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            vtnPrincipal.verMensaje("Error al Guardar la Calificación" + e.toString(), titulo, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNumeroMatricula;
    private javax.swing.JPanel pnlCalificacion;
    private javax.swing.JPanel pnlRegistroCalificaciones;
    private javax.swing.JSpinner snnValor;
    private javax.swing.JTextArea txtDatosMatricula;
    private javax.swing.JTextField txtNumeroMatricula;
    // End of variables declaration//GEN-END:variables
}
